### ISSUE TITLE
当前版本会引发coredump，php7.1.9

### ISSUE THREAD

**Issue by visoeclipse** [wulijun/php-ext-trie-filter#20]
.el7.x86_64 freetype-2.8-12.el7_6.1.x86_64 glibc-2.17-260.el7_6.6.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-37.el7_6.x86_64 libattr-2.4.46-13.el7.x86_64 libcap-2.22-9.el7.x86_64 libcom_err-1.42.9-13.el7.x86_64 libcurl-7.29.0-51.el7_6.3.x86_64 libgcc-4.8.5-36.el7_6.2.x86_64 libidn-1.28-4.el7.x86_64 libjpeg-turbo-1.2.90-6.el7.x86_64 libpng-1.5.13-7.el7_2.x86_64 libselinux-2.5-14.1.el7.x86_64 libssh2-1.4.3-12.el7.x86_64 libstdc++-4.8.5-36.el7_6.2.x86_64 libtool-ltdl-2.4.2-22.el7_3.x86_64 libxml2-2.9.1-6.el7_2.3.x86_64 nspr-4.19.0-1.el7_5.x86_64 nss-3.36.0-7.el7_5.x86_64 nss-softokn-freebl-3.36.0-5.el7_5.x86_64 nss-util-3.36.0-1.el7_5.x86_64 openldap-2.4.44-21.el7_6.x86_64 openssl-libs-1.0.2k-16.el7_6.1.x86_64 pcre-8.32-17.el7.x86_64 sssd-client-1.16.2-13.el7.x86_64 systemd-libs-219-62.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  0x00007f017d95d2c7 in raise () from /lib64/libc.so.6
#1  0x00007f017d95e9b8 in abort () from /lib64/libc.so.6
#2  0x00007f017d99fe17 in __libc_message () from /lib64/libc.so.6
#3  0x00007f017d9a9e16 in _int_malloc () from /lib64/libc.so.6
#4  0x00007f017d9ac32c in malloc () from /lib64/libc.so.6
#5  0x00007f0172cbc153 in trie_new (alpha_map=0x2234730) at trie.c:120
#6  0x00007f0172ec1d12 in zif_trie_filter_new (execute_data=0x7f017a017830, return_value=0x7f017a0177a0) at /home/service/tmp/php_init/trie_filter-master/trie_filter.c:342
#7  0x0000000000a922da in ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER () at /home/service/tmp/php_init/php-7.1.9/Zend/zend_vm_execute.h:675
#8  0x0000000000a919fd in execute_ex (ex=0x7f017a015f70) at /home/service/tmp/php_init/php-7.1.9/Zend/zend_vm_execute.h:429
#9  0x0000000000a1a1cf in zend_call_function (fci=0x7fff05e1bcf0, fci_cache=0x7fff05e1bcc0) at /home/service/tmp/php_init/php-7.1.9/Zend/zend_execute_API.c:855
#10 0x000000000087cc39 in zif_call_user_func_array (execute_data=0x7f017a015f00, return_value=0x7f017a015ef0)
    at /home/service/tmp/php_init/php-7.1.9/ext/standard/basic_functions.c:4860
#11 0x0000000000a92b9c in ZEND_DO_FCALL_BY_NAME_SPEC_RETVAL_USED_HANDLER () at /home/service/tmp/php_init/php-7.1.9/Zend/zend_vm_execute.h:876
#12 0x0000000000a919fd in execute_ex (ex=0x7f017a015030) at /home/service/tmp/php_init/php-7.1.9/Zend/zend_vm_execute.h:429
#13 0x0000000000a91b0f in zend_execute (op_array=0x7f017a087000, return_value=0x0) at /home/service/tmp/php_init/php-7.1.9/Zend/zend_vm_execute.h:474
#14 0x0000000000a33193 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /home/service/tmp/php_init/php-7.1.9/Zend/zend.c:1480
#15 0x00000000009a29ae in php_execute_script (primary_file=0x7fff05e1e3b0) at /home/service/tmp/php_init/php-7.1.9/main/main.c:2552
#16 0x0000000000b21c74 in main (argc=3, argv=0x7fff05e1e5d8) at /home/service/tmp/php_init/php-7.1.9/sapi/fpm/fpm/fpm_main.c:1966

**Comment by visoeclipse** [comment]
gcc (GCC) 4.8.5
